---
# ---------------------------
# Kalliope default settings
# Use YAML syntax
# ---------------------------

# ---------------------------
# Trigger
# ---------------------------
# This is the trigger that will catch your magic work to wake up Kalliope
default_trigger: "porcupine"

# Trigger engine configuration
# Available engine are:
# - snowboy
triggers:
  - snowboy:
      pmdl_file: "trigger/Hey_doyel.pmdl"
  - porcupine:
      keywords:
        - keyword: 
            ppn_file: "trigger/raspberry_raspberrypi_tiny.ppn"
            sensitivity: 0.4
      tiny_keyword: true


# ---------------------------
# Speech to text
# ---------------------------

# This is the STT that will be used by default
default_speech_to_text: "google"

# Spreech to Text engines configuration
# Available engine are:
# - google (via SpeechRecognition)
# - wit
# - bing
# - apiai
# - houndify
# - cmusphinx (must be installed first)
speech_to_text:
  - google:
      language: "bn-BD"
  - cmusphinx:
      language: "bn-BD"
  - wit:
      key: "6XI65JM6MSXPVL72STARIW5YVM3A3ZGQ"
  - apiai:
      key: "5034784d2ac647d581593508078ae00b"
      language: "en"
# ---------------------------
# Text to speech
# ---------------------------
# This is the default TTS that will be used by Kalliope to talk.
default_text_to_speech: "googletts"
# where we store generated audio files from TTS engine to reuse them
cache_path: "/tmp/kalliope_tts_cache"

# Text to Spreech engines configuration
# Available engine are:
# - pico2wave
# - watson
# - pico2wave
# - googletts
# - voicerss
text_to_speech:
  - pico2wave:
      language: "en-US"
      cache: True
  - googletts:
      language: "bn"
      cache: True
  - voicerss:
      language: "en-us"
      cache: True
  - espeak:
      voice: "bn"
  - marytts:
      voice: "cmu-bdl"
      locale: "en_US"
      cache: True
  - watson:
      apikey: "MyRANDOMAPIKEY"
      voice: "fr-FR_ReneeVoice"
      location: "https://stream-fra.watsonplatform.net/text-to-speech/api"

# ---------------------------
# players
# ---------------------------
# This is the sound player that will be used by default
default_player: "mplayer"

# players configuration
# Available engine are:
# - mplayer
# - pyalsaaudio       # no mp3
# - pyaudioplayer     # no mp3
# - sounddeviceplayer # no mp3
players:
  - mplayer: {}
  - pyalsaaudio:
     device: "default"
     convert_to_wav: True
  - pyaudioplayer:
     convert_to_wav: True
  - sounddeviceplayer:
     convert_to_wav: True

# ---------------------------
# Hooks
# ---------------------------
hooks:
  on_start: "on-start-synapse"
  on_waiting_for_trigger:
  on_triggered: "on-triggered-synapse"
  on_start_listening:
  on_stop_listening:
  on_order_found:
  on_order_not_found: "order-not-found-synapse"
  on_processed_synapses:
  on_deaf:
  on_undeaf:
  on_start_speaking:
  on_stop_speaking:
  on_stt_error:

# ---------------------------
# Rest API
# ---------------------------
rest_api:
  active: True
  port: 5000
  password_protected: True
  login: admin
  password: secret
  allowed_cors_origin: "*"

# ---------------------------
# resource directory path
# ---------------------------
resource_directory:
  neuron: "resources/neurons"
  stt: "resources/stt"
  tts: "resources/tts"
  signal: "resources/signal"
  trigger: "resources/trigger"
#

# ---------------------------
# Global files variables
# /!\ If a variable is defined in different files, the last file defines the value.
# ---------------------------
var_files:
  - global_variables/variables.yml
#  - variables2.yml

# -------------
# Options
# -------------
options:
#  energy_threshold: 4000                 # Speech to text option
#  adjust_for_ambient_noise_second: 1     # Speech to text option
#  stt_timeout: 5                          # Speech to text option
  deaf: False
  mute: False

# send hit to anonymously evaluate the global usage of Kalliope app by users
send_anonymous_usage_stats: True
